name: otr_lib
description: On the road app core
version: 0.1.0

environment:
  sdk: ">=2.2.2 <3.0.0"


dependencies:
  provider: ^3.0.0+1
  flutter_swiper: ^1.1.6
  html_unescape: ^1.0.1+3
  either_option: ^1.0.3
  flushbar: ^1.8.2
  flutter_html: ^0.10.4

  # awesome Http client
  dio: ^2.1.13
  # for caching some heavy http request
  dio_http_cache: ^0.1.3

  cached_network_image: ^1.1.1

  sqflite: ^1.1.6

  path_provider: ^1.2.0
  url_launcher: ^5.1.2

  intl: ^0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
